---
values:
  - name: screenHeight
    type: integer
    data: 400
    scope: global
  - name: screenWeight
    type: integer
    data: 400
    scope: global
  - name: gameTitle
    type: string
    data: game
    scope: local


