---
values:


  - name: ib1
    type: string
    data: default|b1.0.png
    scope: local

  - name: ib2
    type: string
    data: default|b1.1.png
    scope: local

  - name: iboss1background
    type: string
    data: boss|Hintergrund/Boss1.png
    scope: local
